version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: tinder_service
      POSTGRES_DB: tinder_service
    ports:
      - 127.0.0.1:5432:5432