spring:
  datasource:
    jdbc-url: jdbc:postgresql://ec2-3-223-213-207.compute-1.amazonaws.com:5432/d93g4h8bnv65q0
    username: geriewfzcnosxt
    password: 0a9f4f0b4eaf42d523ee63ddf474a3db11200f3933bd75f6b97b476d226ad261
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    location: classpath:db/migration
    enabled: true
    user: geriewfzcnosxt
    password: 0a9f4f0b4eaf42d523ee63ddf474a3db11200f3933bd75f6b97b476d226ad261


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher