/*
 * This file is generated by jOOQ.
 */
package com.pl.sggw.tinder.jooq.tables


import com.pl.sggw.tinder.jooq.Public
import com.pl.sggw.tinder.jooq.keys.USER_PREFERENCES_USER_EMAIL_KEY
import com.pl.sggw.tinder.jooq.tables.records.UserPreferencesRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserPreferences(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, UserPreferencesRecord>?,
    aliased: Table<UserPreferencesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<UserPreferencesRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.user_preferences</code>
         */
        val USER_PREFERENCES = UserPreferences()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UserPreferencesRecord> = UserPreferencesRecord::class.java

    /**
     * The column <code>public.user_preferences.user_email</code>.
     */
    val USER_EMAIL: TableField<UserPreferencesRecord, String?> = createField(DSL.name("user_email"), SQLDataType.VARCHAR(126), this, "")

    /**
     * The column <code>public.user_preferences.gender</code>.
     */
    val GENDER: TableField<UserPreferencesRecord, String?> = createField(DSL.name("gender"), SQLDataType.VARCHAR(6), this, "")

    /**
     * The column <code>public.user_preferences.min_age</code>.
     */
    val MIN_AGE: TableField<UserPreferencesRecord, Short?> = createField(DSL.name("min_age"), SQLDataType.SMALLINT, this, "")

    /**
     * The column <code>public.user_preferences.max_age</code>.
     */
    val MAX_AGE: TableField<UserPreferencesRecord, Short?> = createField(DSL.name("max_age"), SQLDataType.SMALLINT, this, "")

    /**
     * The column <code>public.user_preferences.creation_timestamp</code>.
     */
    val CREATION_TIMESTAMP: TableField<UserPreferencesRecord, LocalDateTime?> = createField(DSL.name("creation_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.user_preferences.modification_timestamp</code>.
     */
    val MODIFICATION_TIMESTAMP: TableField<UserPreferencesRecord, LocalDateTime?> = createField(DSL.name("modification_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<UserPreferencesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<UserPreferencesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.user_preferences</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.user_preferences</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.user_preferences</code> table reference
     */
    constructor(): this(DSL.name("user_preferences"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, UserPreferencesRecord>): this(Internal.createPathAlias(child, key), child, key, USER_PREFERENCES, null)
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getKeys(): List<UniqueKey<UserPreferencesRecord>> = listOf(USER_PREFERENCES_USER_EMAIL_KEY)
    override fun `as`(alias: String): UserPreferences = UserPreferences(DSL.name(alias), this)
    override fun `as`(alias: Name): UserPreferences = UserPreferences(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserPreferences = UserPreferences(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserPreferences = UserPreferences(name, null)

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row6<String?, String?, Short?, Short?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row6<String?, String?, Short?, Short?, LocalDateTime?, LocalDateTime?>
}
