/*
 * This file is generated by jOOQ.
 */
package com.pl.sggw.tinder.jooq.tables.references


import com.pl.sggw.tinder.jooq.tables.TinderUser
import com.pl.sggw.tinder.jooq.tables.UserMatchDecition
import com.pl.sggw.tinder.jooq.tables.UserPreferences



/**
 * The table <code>public.tinder_user</code>.
 */
val TINDER_USER = TinderUser.TINDER_USER

/**
 * The table <code>public.user_match_decition</code>.
 */
val USER_MATCH_DECITION = UserMatchDecition.USER_MATCH_DECITION

/**
 * The table <code>public.user_preferences</code>.
 */
val USER_PREFERENCES = UserPreferences.USER_PREFERENCES
