/*
 * This file is generated by jOOQ.
 */
package com.pl.sggw.tinder.jooq.keys


import com.pl.sggw.tinder.jooq.tables.TinderUser
import com.pl.sggw.tinder.jooq.tables.UserMatchDecition
import com.pl.sggw.tinder.jooq.tables.UserPreferences
import com.pl.sggw.tinder.jooq.tables.records.TinderUserRecord
import com.pl.sggw.tinder.jooq.tables.records.UserMatchDecitionRecord
import com.pl.sggw.tinder.jooq.tables.records.UserPreferencesRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val TINDER_USER_PKEY: UniqueKey<TinderUserRecord> = Internal.createUniqueKey(TinderUser.TINDER_USER, DSL.name("tinder_user_pkey"), arrayOf(TinderUser.TINDER_USER.ID), true)
val TINDER_USER_USER_EMAIL_KEY: UniqueKey<TinderUserRecord> = Internal.createUniqueKey(TinderUser.TINDER_USER, DSL.name("tinder_user_user_email_key"), arrayOf(TinderUser.TINDER_USER.USER_EMAIL), true)
val USER_MATCH_DECITION_PKEY: UniqueKey<UserMatchDecitionRecord> = Internal.createUniqueKey(UserMatchDecition.USER_MATCH_DECITION, DSL.name("user_match_decition_pkey"), arrayOf(UserMatchDecition.USER_MATCH_DECITION.ID), true)
val USER_PREFERENCES_USER_EMAIL_KEY: UniqueKey<UserPreferencesRecord> = Internal.createUniqueKey(UserPreferences.USER_PREFERENCES, DSL.name("user_preferences_user_email_key"), arrayOf(UserPreferences.USER_PREFERENCES.USER_EMAIL), true)
